version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    environment:
      - name=value
      - MONGO_DB = recommender_db
      - MONGO_PORT = 27017
      - MONGO_HOST = mongodb

      - APP_HOST = 0.0.0.0
      - APP_PORT = 8000

      - PYTHONPATH= .
    ports:
      - 8000:8000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: