name: Recommender CI/CD Pipeline

on:
  pull_request:
    branches:
    - master
    paths:
    - app/**
    - tests/**

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: pip

    - name: Install tox
      run: pip install --user tox

    - name: Run tests and lint
      run: tox
