name: Recommender CI/CD Pipeline

on:
  push:
    branches:
    - master

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: pip

    - name: Install tox
      run: pip install --user tox

    - name: Run tests and lint
      run: tox

  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    if: github.ref == 'refs/heads/master'
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      env:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Login to ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1

    - name: Creating Docker Image
      run: docker build -t {{env.DOCKER_IMAGE}} .

    - name: Tagging Image
      run: docker tag ${{env.DOCKER_IMAGE}}:latest {{env.DOCKER_REPOSITORY}}:latest

    - name: Pushing image
      run: docker push ${{env.DOCKER_REPOSITORY}}:latest
