name: Recommender CI/CD Pipeline

on:
  push:
    branches:
    - master

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: pip

    - name: Install tox
      run: pip install --user tox

    - name: Run tests and lint
      run: tox

  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    env:
      DOCKER_IMAGE: ${{env.DOCKER_IMAGE}}
      DOCKER_REPOSITORY: ${{env.DOCKER_REPOSITORY}}

    if: github.ref == 'refs/heads/master'
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2 # More information on this action can be found below in the 'AWS Credentials' section
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    - name: Login to ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1

    - name: Creating Docker Image
      run: docker build -t $DOCKER_IMAGE .

    - name: Tagging Image
      run: docker tag $DOCKER_IMAGE:latest $DOCKER_REPOSITORY:latest

    - name: Pushing image
      run: docker push $DOCKER_REPOSITORY:latest
